import 'package:path/path.dart' as p;

const generatedHeader = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by package:barrel_gen.
''';

/// Formats deterministic standalone Dart export libraries.
final class BarrelFormat {
  const BarrelFormat();

  bool isGenerated(String contents) => contents.startsWith(generatedHeader);

  String render({
    required List<String> sourcePaths,
    required String outputPath,
  }) {
    final exports =
        sourcePaths
            .map((sourcePath) => _formatExport(sourcePath, outputPath))
            .toList(growable: false)
          ..sort();

    return '$generatedHeader\n${exports.join('\n')}\n';
  }

  String _formatExport(String sourcePath, String outputPath) {
    final relativePath = p
        .relative(sourcePath, from: p.dirname(outputPath))
        .replaceAll(p.separator, '/');
    final escapedPath = relativePath.replaceAll("'", "\\'");

    return "export '$escapedPath';";
  }
}
